### PR TITLE
Made SmartApps function with IDE

### PR DESCRIPTION
**Pull request by snakedog116**
Changed folder structure, and made names lowercase.
Changed all namespaces to eco-community

### CODE REVIEW

**Comment by StrykerSKS** [comment]
Hmmm, seems that GIT does not handle renamed files and directories very well across multiple contributors! I'll have to spend some time cleaning this up this weekend.

**Comment by snakedog116** [comment]
Sorry. I thought you weren't touching it until the weekend. 

Can you give me access to make changes directly?

**Comment by StrykerSKS** [comment]
I added you as a collaborator.

I'm in the files now doing a lot of updates, so things may move around a
bit and lots of (minor hopefully) changes coming tonight so that I can
announce the repository by tomorrow.

// Sean

**Comment by snakedog116** [comment]
Thanks.

I just hope changing the names of the apps doesn't kill anything.

I did try to change the name of the EcobeeInit by putting a space in the name and it didn't seem to work anymore. I'm wondering if the codes refer to other codes by name. Is that possible? or are they all sandboxed? Somehow the EcobeeInit app knows which device to create, so I figure they must be able to reference each other somehow.

**Pull request merged**
